# This docker simulates a production environment for blue-eyed

services:
    redis:
        image: redis:7.0.11-alpine
        ports:
            - 6379:6379
        restart: unless-stopped

    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: blue-eyed
        ports:
            - 5432:5432
        restart: unless-stopped

    traefik:
        image: traefik:latest
        command:
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.web.address=:80'
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.traefik.rule=Host(`traefik.localhost`)'
            - 'traefik.http.routers.traefik.service=api@internal'
            - 'traefik.http.routers.traefik.entrypoints=web'
            - 'traefik.http.routers.traefik.middlewares=blue-eyed@docker'

    whoami:
        image: traefik/whoami
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.whoami.rule=Host(`whoami.localhost`)'
            - 'traefik.http.routers.whoami.entrypoints=web'
            - 'traefik.http.routers.whoami.middlewares=blue-eyed@docker'
        restart: unless-stopped

    blue-eyed:
        image: blue-eyed:dev
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/blue-eyed
            REDIS_URL: redis://redis:6379
            SERVICE_HOSTNAME: http://auth.localhost
        expose:
            - 3000
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.auth.rule=Host(`auth.localhost`) || HostRegexp(`{subdomain:[a-z0-9-]+}.localhost`) && PathPrefix(`/auth.blue-eyed/`)'
            - 'traefik.http.routers.auth.entrypoints=web'

            - 'traefik.http.middlewares.blue-eyed.forwardauth.address=http://blue-eyed:3000/auth/traefik'
            - 'traefik.http.middlewares.blue-eyed.forwardauth.trustForwardHeader=true'
            - 'traefik.http.middlewares.blue-eyed.forwardauth.authResponseHeaders=X-Auth-User, X-Secret, authorization'
